FROM traefik:2.7.1

LABEL org.opencontainers.image.authors="Hofmann, Benjamin <hb@beohof.de>"

ENV TRAEFIK_API=false
ENV TRAEFIK_PROVIDERS_FILE_FILENAME=/etc/traefik/dynamic.yml
ENV TRAEFIK_ENTRYPOINTS_WEB_ADDRESS=:80
ENV TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_TO=websecure
ENV TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS=:443
ENV TRAEFIK_ENTRYPOINTS_WEBSECURE_HTTP_TLS_CERTRESOLVER=le
ENV TRAEFIK_CERTIFICATESRESOLVERS_LE_ACME_DNSCHALLENGE=true
ENV TRAEFIK_CERTIFICATESRESOLVERS_LE_ACME_DNSCHALLENGE_PROVIDER=hetzner
ENV TRAEFIK_CERTIFICATESRESOLVERS_LE_ACME_STORAGE=/acme.json

ADD ./dynamic.yml /etc/traefik/dynamic.yml